spring.application.name=DUWASA-FAMS

spring.datasource.url=jdbc:postgresql://localhost:5432/duwasa_fams
spring.datasource.username=postgres
spring.datasource.password=123456

spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
jwt.secret=DUWASA_FAMS_SECRET_KEY_2026_THIS_MUST_BE_AT_LEAST_32_CHARACTERS_LONG
jwt.expiration=86400000
app.initial-admin.email=admin@duwasa.go.tz
app.initial-admin.password=Admin@12345